# Task 3 : OpenHygrisC Nitrate Data

## Aim of This notebook 

The aim of this notebook is to create two shape file from the tables that we have already in our database.

In [67]:
import pandas as pd
import psycopg2
import credential_temp as  creds 
import geopandas as gpd

## Connect to the Database

In [68]:
# connect to our credentioal file
conn_string = "host=" + creds.PGHOST + " port=" + creds.PORT + " dbname=" + creds.PGDATABASE + " user=" + creds.PGUSER \
    + " password=" + creds.PGPASSWORD

In [69]:
conn = psycopg2.connect(conn_string)

## Read the table from database

In this step, we need to read the messstelle table which is already in our database to the pandas dataframe.

In [70]:
quary = """ select * from hygrisc.messstelle """

In [71]:
df = pd.read_sql(quary, conn,)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11832\1697117798.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(quary, conn,)

## Drop the geom column

The table has "geom" column which consist of the geometry information from e32 and n32 columns but we need to delete this column and create this column with another format which can be transfered to geopandas datafarme.

In [72]:
df.drop('geom', axis = 1, inplace = True)

## Essentioanl packages which need for geopandas dataframe

In [73]:
import geopandas as gpd
from shapely.geometry import Point

## Create geodata frame

with the helpf of geopandas we can create geo pandas dataframe. in here simply we can create the geometry column again but with another method.

In [74]:
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.e32, df.n32), crs="EPSG:25832")

In [75]:
gdf

,sl_nr,messstelle_id,name,e32,n32,gw_stockwerk,grundstueck,gemeinde_id,gemeinde_name,gwhorizont_id,...,eigentuemer,betreiber,filterlaenge_cm,sumpfrohrlaenge_cm,ausbaudurchmesser_mm,historischer_ruhe_wsp,einbaulaenge_cm,oberkante_filter_cm,unterkante_filter_cm,geometry
0,67096,129903164,ROHBURGFELD HERRENW,456943,5656177,NaN,oeffentlich,5970004,Bad Berleburg,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,POINT (456943 5656177)
1,69233,42066750,LINEG_2843,340456,5700994,1.0,,05112000,Duisburg,None,...,None,None,NaN,NaN,125.0,None,2005.0,753.0,753.0,POINT (340456 5700994)
2,4124,98120219,Dep. Ha. B-H GWD 1,412580,5725932,NaN,oeffentlich,5915000,Hamm,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,POINT (412580 5725932)
3,46667,94130255,Br.7 kurze Reihe,421848,5705096,NaN,oeffentlich,5974056,Wickede (Ruhr),None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,POINT (421848 5705096)
4,59793,39900368,Brucknerstraße,351865,5669341,1.0,oeffentlich,5111000,Düsseldorf,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,POINT (351865 5669341)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6767,38425,278157312,Kaster,329037,5653597,NaN,oeffentlich,5362004,Bedburg,4,...,RWE Power AG ...,RWE Power AG ...,1000.0,600.0,125.0,None,21615.0,-14001.0,-15001.0,POINT (329037 5653597)
6768,53227,279380513,Glessen,340027,5648873,1.0,oeffentlich,5362008,Bergheim,2,...,Erftverband ...,Erftverband ...,200.0,200.0,65.0,None,2913.0,9701.0,9501.0,POINT (340027 5648873)
6769,9849,42011139,LINEG_1254,333564,5709155,1.0,privat,5170024,Moers,None,...,Lineg ...,Lineg ...,NaN,NaN,125.0,None,2170.0,182.0,182.0,POINT (333564 5709155)
6770,69228,46068387,LINEG_2999H,323940,5711001,1.0,,5170020,Kamp-Lintfort,None,...,LINEG_neu ...,None,NaN,NaN,NaN,None,1000.0,1065.0,1065.0,POINT (323940 5711001)
6771,45723,289100616,Knechtst. P 1-4,341853,5660527,1.0,privat,5162028,Rommerskirchen,19,...,Erftverband ...,Erftverband ...,500.0,300.0,50.0,None,3060.0,2099.0,1599.0,POINT (341853 5660527)

## Create the path of output

In [76]:
data_in_dir = r"data"

file_fname = r"messstelle_local.gpkg"

file_pfname = data_in_dir + '/' +file_fname

## Create the shape file in the above path

In [77]:


gdf.to_file(file_pfname, layer='messstelle_local', driver="GPKG")

## Second shape file.
Now we want to create the second shape file.

* This shape file is a little bit complex than the previous one

## Read the table from Database

We don't want all the rows in messwert table, we want only nitrate and the nitrate stoff number is 1244

In [78]:
quary2 = """ select * from hygrisc.messwert where stoff_nr = '1244' """

In [79]:
df1 = pd.read_sql(quary2, conn,)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11832\3591153979.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql(quary2, conn,)

In [80]:
df1

,messstelle_id,messstelle_sl_nr,datum_pn,stoff_nr,probengut,messergebnis_c,messergebnis_hinweis,bestimmungsgrenze,masseinheit,trennverfahren,verfahren,vor_ort,messergebnis_cm
0,42018808,10612,1966-04-12,1244,Grundwasser,1200000.0,...,None,mg/l,Gesamtgehalt,DIN 38405-9 (1979),,=
1,42018808,10612,1967-10-10,1244,Grundwasser,100002.0,Konzentration zu gering zur Bestimmung ...,None,mg/l,Gesamtgehalt,DIN 38405-9 (1979),,<
2,94160090,24635,1965-06-15,1244,Grundwasser,899996.0,...,None,mg/l,Gesamtgehalt,None,,=
3,42018808,10612,1967-07-24,1244,Grundwasser,1000002.0,...,None,mg/l,Gesamtgehalt,DIN 38405-9 (1979),,=
4,94160090,24635,1966-09-15,1244,Grundwasser,1099999.0,...,None,mg/l,Gesamtgehalt,None,,=
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106805,60240027,13094,2022-05-31,1244,Grundwasser,133000.0,Konzentration zu gering zur Bestimmung ...,"1,33000",mg/l,Gesamtgehalt,DIN ISO 15923-1 - DI - D49 - 1,,<
106806,60240155,55652,2022-11-23,1244,Grundwasser,3705000.0,...,None,mg/l,Gesamtgehalt,DIN ISO 15923-1 - DI - D49 - 1,,=
106807,80302944,46970,2022-05-06,1244,Grundwasser,753000.0,...,None,mg/l,Gesamtgehalt,DIN ISO 15923-1 - DI - D49 - 1,,=
106808,110039830,70878,2022-06-30,1244,Grundwasser,133000.0,Konzentration zu gering zur Bestimmung ...,"1,33000",mg/l,Gesamtgehalt,DIN ISO 15923-1 - DI - D49 - 1,,<
106809,60220909,13063,2022-06-30,1244,Grundwasser,2355000.0,...,None,mg/l,Gesamtgehalt,DIN ISO 15923-1 - DI - D49 - 1,,=

## Merge the data

In [81]:
df1_n = df1[[ 'messstelle_id', 'datum_pn', 'stoff_nr', 'messergebnis_c', 'messergebnis_hinweis', 'messergebnis_cm']]

In [82]:
gdf_n = gdf[['messstelle_id', 'name', 'gemeinde_id', 'geometry' ]]

In [83]:
df_merg = pd.merge(df1_n, gdf_n, on = ['messstelle_id'])

In [84]:
df_merg

,messstelle_id,datum_pn,stoff_nr,messergebnis_c,messergebnis_hinweis,messergebnis_cm,name,gemeinde_id,geometry
0,42018808,1966-04-12,1244,1200000.0,...,=,LINEG_1658-1H,5170020,POINT (328299 5706506)
1,42018808,1967-10-10,1244,100002.0,Konzentration zu gering zur Bestimmung ...,<,LINEG_1658-1H,5170020,POINT (328299 5706506)
2,42018808,1967-07-24,1244,1000002.0,...,=,LINEG_1658-1H,5170020,POINT (328299 5706506)
3,42018808,1966-10-11,1244,1399999.0,...,=,LINEG_1658-1H,5170020,POINT (328299 5706506)
4,42018808,1968-01-16,1244,100002.0,Konzentration zu gering zur Bestimmung ...,<,LINEG_1658-1H,5170020,POINT (328299 5706506)
...,...,...,...,...,...,...,...,...,...
59605,69000232,2024-07-30,1244,168400.0,...,=,EGLV 7441240,05512000,POINT (351711 5715813)
59606,82062018,2023-03-23,1244,20807000.0,...,=,LINEG_2411,5154020,POINT (321912 5716465)
59607,82062018,2023-03-23,1244,21000000.0,...,=,LINEG_2411,5154020,POINT (321912 5716465)
59608,82062018,2022-03-25,1244,21692000.0,...,=,LINEG_2411,5154020,POINT (321912 5716465)
59609,82062018,2022-03-25,1244,21600000.0,...,=,LINEG_2411,5154020,POINT (321912 5716465)

## change the type of "datum_pn" to datetime

In [85]:
df_merg['datum_pn'] = pd.to_datetime(df_merg['datum_pn'], format = '%Y-%m-%d')

In [86]:
df_merg.dtypes

messstelle_id                    int64
datum_pn                datetime64[ns]
stoff_nr                         int64
messergebnis_c                 float64
messergebnis_hinweis            object
messergebnis_cm                 object
name                            object
gemeinde_id                     object
geometry                      geometry
dtype: object

## create the geometry column

In [87]:
gdf_merg = gpd.GeoDataFrame(df_merg, geometry= 'geometry', crs="EPSG:25832")

In [88]:
gdf_merg.dtypes

messstelle_id                    int64
datum_pn                datetime64[ns]
stoff_nr                         int64
messergebnis_c                 float64
messergebnis_hinweis            object
messergebnis_cm                 object
name                            object
gemeinde_id                     object
geometry                      geometry
dtype: object

## Path directory for output

In [89]:
data_in_dir = r"data"

file_fname = r"nitrat_local.gpkg"

file_pfname = data_in_dir + '/' +file_fname

## Create shape file

In [90]:
gdf_merg.to_file(file_pfname, layer='nitrat_local', driver="GPKG")

In [91]:
import geopandas as gpd

# Load the messstelle_local.gpkg
gdf_messstelle = gpd.read_file("data/messstelle_local.gpkg", layer='messstelle_local')
print(gdf_messstelle.head())

# Load the nitrat_local.gpkg
gdf_nitrat = gpd.read_file("data/nitrat_local.gpkg", layer='nitrat_local')
print(gdf_nitrat.head())

   sl_nr  messstelle_id                 name     e32      n32  gw_stockwerk  \
0  67096      129903164  ROHBURGFELD HERRENW  456943  5656177           NaN
1  69233       42066750  LINEG_2843           340456  5700994           1.0
2   4124       98120219  Dep. Ha. B-H GWD 1   412580  5725932           NaN
3  46667       94130255  Br.7 kurze Reihe     421848  5705096           NaN
4  59793       39900368  Brucknerstraße       351865  5669341           1.0

   grundstueck gemeinde_id   gemeinde_name gwhorizont_id  ... eigentuemer  \
0  oeffentlich     5970004   Bad Berleburg          None  ...        None
1                 05112000        Duisburg          None  ...        None
2  oeffentlich     5915000            Hamm          None  ...        None
3  oeffentlich     5974056  Wickede (Ruhr)          None  ...        None
4  oeffentlich     5111000      Düsseldorf          None  ...        None

  betreiber filterlaenge_cm sumpfrohrlaenge_cm ausbaudurchmesser_mm  \
0      None             NaN                NaN                  NaN
1      None             NaN                NaN                125.0
2      None             NaN                NaN                  NaN
3      None             NaN                NaN                  NaN
4      None             NaN                NaN                  NaN

  historischer_ruhe_wsp einbaulaenge_cm oberkante_filter_cm  \
0                  None             NaN                 NaN
1                  None          2005.0               753.0
2                  None             NaN                 NaN
3                  None             NaN                 NaN
4                  None             NaN                 NaN

  unterkante_filter_cm                geometry
0                  NaN  POINT (456943 5656177)
1                753.0  POINT (340456 5700994)
2                  NaN  POINT (412580 5725932)
3                  NaN  POINT (421848 5705096)
4                  NaN  POINT (351865 5669341)

[5 rows x 41 columns]
   messstelle_id   datum_pn  stoff_nr  messergebnis_c  \
0       42018808 1966-04-12      1244       1200000.0
1       42018808 1967-10-10      1244        100002.0
2       42018808 1967-07-24      1244       1000002.0
3       42018808 1966-10-11      1244       1399999.0
4       42018808 1968-01-16      1244        100002.0

                                messergebnis_hinweis messergebnis_cm  \
0                                                ...               =
1  Konzentration zu gering zur Bestimmung        ...               <
2                                                ...               =
3                                                ...               =
4  Konzentration zu gering zur Bestimmung        ...               <

                  name gemeinde_id                geometry
0  LINEG_1658-1H           5170020  POINT (328299 5706506)
1  LINEG_1658-1H           5170020  POINT (328299 5706506)
2  LINEG_1658-1H           5170020  POINT (328299 5706506)
3  LINEG_1658-1H           5170020  POINT (328299 5706506)
4  LINEG_1658-1H           5170020  POINT (328299 5706506)

# Finish !
## Good Luck, You are doing well